### ISSUE TITLE
Configurations Not loading for the connector

### ISSUE THREAD

**Issue by CC-isha** [MuleChain-Project/mulechain-ai-connector#19]
Description:
I am encountering an issue with the MuleChain Connector version 0.2.0 where the configurations do not seem to load properly. Despite multiple refreshes and attempts to reload, the configurations fail to appear.

Steps to Reproduce:

Install MuleChain Connector version 0.2.0.
Open the connector configuration settings.
Attempt to load the configurations.
Refresh the configurations multiple times.
Expected Behavior:
The configurations should load successfully upon refreshing.

Actual Behavior:
The configurations do not load, even after multiple refresh attempts.

Environment:

MuleChain Connector version: 0.2.0
Mule runtime : 4.6.1
OS : Windows

![image](https://github.com/user-attachments/assets/b24a02e9-080d-478e-99c6-361486c5b3a8)

**Comment by amirkhan-ak-sf** [comment]
Hi @arpitg-1 

I sometimes have the same issue, but mostly when my machine is on heavy CPU usage due to Slack, Google Meet, etc. I thought it was only me, but looks like other users are also facing the issue. Any idea?

**Comment by arpitg-1** [comment]
Hi,

Just wanted to know few things to debug further.

- Is this occurring only for "Model Name"? If so, can we try to select "Llm type" explicitly and then check on "Model Name".
- How many times can we reproduce?

**Comment by CC-isha** [comment]
Hi Aprit,

It is occurring for all the configuration, however I am able to work with
the connector by typing all the configuration manually. I have also tried
on my other windows systems to check this issue and got the same result.

Regards,
Isha Sharma
*Solution Consultant* | +91 7439185286 | *Linkedin*
<https://www.linkedin.com/in/isha-sharma-004728201/>

**Comment by arpitg-1** [comment]
Hi Isha,

We need to convert the configuration from static to dynamic one and then resolve values. Please find the steps as mentioned below for a quick fix to this.

Steps:

1. Make any non-list config parameter to contain data weave values. For eg: lets take File Path & click on "fx"
2. Provide some dummy value inside the text box, eg: envVars.json
3. Try to refresh the config values for Llm Type and others.
4. After this the values will be cached, then we can remove value in “File Path”

We are currently working on the permanent fix.

**Comment by CC-isha** [comment]
Hi Arpit,

Just tried it out, that seems to have done the trick for now. Looking
forward to the permanent fix!
Thanks!

Regards,
Isha Sharma
*Solution Consultant* | +91 7439185286 | *Linkedin*
<https://www.linkedin.com/in/isha-sharma-004728201/>
