### ISSUE TITLE
Rag load document fails with file type 'url' in 0.2.0 and up

### ISSUE THREAD

**Issue by MartijnvdB** [MuleChain-Project/mulechain-ai-connector#20]
### Description

I made a Mule project for all operations except _Tools_ in mulechain-ai-connector 0.1.0 and they all worked fine, thanks for providing this library!

Today I upgraded to version 0.2.0 and after changing the code a bit for the new response formats, the only operation that still gives problems is _Rag load document_ with a file type of 'url'. 

This operation throws the following stack trace:

``
Root Exception stack trace:
java.lang.ClassNotFoundException: org.jsoup.nodes.Element
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at org.mule.runtime.module.artifact.api.classloader.FineGrainedControlClassLoader.findLocalClass(FineGrainedControlClassLoader.java:175)
	at org.mule.runtime.module.artifact.api.classloader.FineGrainedControlClassLoader.loadClass(FineGrainedControlClassLoader.java:87)
	at org.mule.runtime.module.artifact.api.classloader.MuleArtifactClassLoader.loadClass(MuleArtifactClassLoader.java:274)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
``

I added a dependency for _org.jsoup_ (that I thought might be missing somewhere) to my Mule project but that did not solve the issue. 

I tried 0.2.13 and it exhibits the same issue.

### How to reproduce

- configure _Rag load document_  (using gpt-3.5-turbo)
- send in a query and a valid URL
- exception occurs

![hc_2181](https://github.com/user-attachments/assets/631c5a60-3b3d-4989-985e-78f3e5eb6b56)

request payload:
`{
    "query": "What is today's top story?",
    "url": "https://nos.nl/sport"
`
### Environment

- Anypoint Studio 7.18.1
- Mule runtime 4.6.6
- Java 8
- Maven 3.8.8
- Windows 10

### Logging
Mule error context and stack trace attached.

[mule-error.json](https://github.com/user-attachments/files/16523288/mule-error.json)
[stacktrace.txt](https://github.com/user-attachments/files/16523304/stacktrace.txt)

**Comment by amirkhan-ak-sf** [comment]
Hi @MartijnvdB 

can you add this dependency to the application pom which you upgraded to 0.2.0.

```
        <dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.16.1</version>
		</dependency> 
```

Let me know if this is fixed. 

Thanks,
Amir

**Comment by MartijnvdB** [comment]
Hi Amir,

Thanks for your reply. Adding that dependency to the pom.xml of my project did not fix the issue:

![image](https://github.com/user-attachments/assets/3219f421-5ca2-4807-a51e-9d467ab262b5)

**Comment by amirkhan-ak-sf** [comment]
Hi @MartijnvdB 
Can you try to add additionally the following to your application.pom's build tag? 

**Add jsoup plugin in the build tag.**

```
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.2.0</version>
			</plugin>
			
			<!--  JSOUP DEPENDENCY -->
           <plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<version>${mule.maven.plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<sharedLibraries>
						<sharedLibrary>
							<groupId>org.jsoup</groupId>
							<artifactId>jsoup</artifactId>
						</sharedLibrary>
					</sharedLibraries>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

**Comment by amirkhan-ak-sf** [comment]
Thanks for the feedback Martin!

yes, it is the change we did in the architecture. Still need to document it. 
And no issue on your side, just the way we handle dependencies at our end to make the connector more stable.
